apiVersion: apps/28
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskctn
        image: gurmindersingh5/flask:v44
        ports:
        - containerPort: 8111

